### PR TITLE
Adding Social Tab and Navlinks

### LINKED ISSUE #188: Telegram and Discord Icons in Navigation Header
P125
https://dao.effect.network/proposals/125

In the navigation bar, display two icons one for the official Effect Network discord and another for the DAO Telegram. When click the user is navigated to the respective locations.

### PR DESCRIPTION
**Pull request by MiggySmallz**
This should satisfy the requirements set in DAO proposal 125.
Resolves #188  and #189

### CODE REVIEW

**Comment by MiggySmallz** [comment]
@djmbritt @jeisses @laurensV

**Comment by djstrikanova** [comment]
> Nice work @MiggySmallz. I like the way this looks!
> 
> But I think it's a bit confusing to me to have a list of other projects listed directly under "Socials". The primary intention of a user clicking socials would be to would be to find links directly related to the project.
> 
> I suggest we make 2 additions:
> 
> * Add a short paragraph/heading in the top with the text "Other DAO endorsed entities in the EOS space"
> * Show a list our own socials in the top (websites, docs, github, etc).

I'd say the "Resources" page covers those links, and the icons cover our social links. Though I guess, a better name than Socials could be used. I can't think of a good word for it though. Endorsements?

**Comment by djstrikanova** [comment]
I think the commit accurately follows the intent of the proposal, so I think it's good to commit this as is. The "Socials" tab I see as being changed periodically as there may be other entities we want to endorse in the EOS space. So in the meanwhile we can decide if we want to revamp the resources page or change the name, et cetera.

**Comment by djmbritt** [comment]
I agree with Jesse here that it would be nice to have some more clarification for this page. True, it does accurately follow the proposal, but we should keep new users in mind as well and the add some extra information about why the page exists.

One more thing is that the Telegram and Discord links in the header make the header row too long. Now the header does not collapse properly on certain widths.

image
image

image

**Comment by jeisses** [comment]
I've made some small adjustments and I think it's good to be merged then.
I've also hidden the "Swap" tab from the menu so we can debug / fine tune any issues with that without exposing it to users directly.

One thing bugging me is that we use a MS Word file icon for links to endorsed website. I did not understand the Font-Awesome Vue module well enough to change this is a website icon, does anyone know how to accomplish that?

**Comment by MiggySmallz** [comment]
@jeisses I used the word file icon more as a placeholder as I didn't really know what else to use. I changed it to a couple different options. Do you prefer any of these? If not, just send a link of a fontawesome icon you would rather have. 
image

**Comment by jeisses** [comment]
I was trying the [`browser` icon](https://fontawesome.com/icons/browser?s=solid&f=classic) and a few others. I guess that one is premium one, kinda weird there is not a clear free website icon in there.
I will merge this for now and we will keep making updates as we go. 
Thanks @MiggySmallz ! :raised_hands:

**Comment by jeisses** [comment]
Aha, I just figured out the fa icons we use need to be added to nuxt config

**Pull request merged**
