### PR TITLE
added comment section to proposals

### LINKED ISSUE #182: Add list of comments on proposal page
For each proposal, add a list of comments, that users can see easily.
Instead of going through each vote and seeing the associated comment.

### PR DESCRIPTION
**Pull request by MiggySmallz**
Resolves #182

### CODE REVIEW

**Review by djmbritt — APPROVED** [review]

**Comment by djmbritt** [comment]
How much do you want for this Miguel?

**Comment by MiggySmallz** [comment]
Just pushed another little addition to this PR which resolves #162. 
I was thinking 10,000 - 15,000 EFX for this PR @djmbritt?

**Comment by jeisses** [comment]
Sound reasonable, and the PR looks good! 👌 

If you could resolve the conflicts then I will merge this

**Comment by djmbritt** [comment]
Fixed 🏁

**Comment by djmbritt** [comment]
Indeed that sounds good!

**Comment by djmbritt** [comment]
https://bloks.io/msig/cryptonode42/commentlistda

**Pull request merged**
